trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'MyACRServiceConnection'   # Service connection ke ACR
    command: 'login'

- script: |
    docker pull youracr.azurecr.io/agentravel:latest
    docker stop agentravel || true
    docker rm agentravel || true
    docker run -d --name agentravel -p 80:3000 youracr.azurecr.io/agentravel:latest
  displayName: 'Deploy Docker Container'
